#version: "3"
services:
  gpt_agent:
    container_name: indyco_agent
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./resources/:/llm4bi/resources/
      - ./output/:/llm4bi/output/
    command:
      - /bin/bash
      - -c
      - |
        python3 src/test/testGPTAgent.py