-- ----------------------------------------------------------------
--          Indyco Builder - Auto-Generated DDL Script           --
-- ----------------------------------------------------------------
--
-- Project Name . . . . . . : Indyco Tutorial
--  + Exported Datamarts. . : Commercial, Sale, Inventory
--  + Export Timestamp. . . : 2025-10-28 10:04:33
--
-- Selected Profile . . . . : Star Schema
--  + Shared Hierarchies. . : Snowflake
--  + Cross Dimensional Attr: Bridge table without surrogates
--  + Degenerate Dimensions : Use fact table
--  + Multiple Arcs . . . . : Bridge table without surrogates
--  + Recursions. . . . . . : Use self-referencing keys
--
-- Target DB. . . . . . . . : PostgreSQL
--  + Export Primary Keys . : True
--  + Export Foreign Keys . : True
--  + Nullable columns. . . : True
--
-- ----------------------------------------------------------------

CREATE TABLE "DT_AGENT"
(
  "ID_AGENT" INTEGER NOT NULL,
  "AGENT" VARCHAR (255),
  "AREA_MANAGER" VARCHAR (255),
  "ID_AREA_MANAGER" INTEGER
);
ALTER TABLE "DT_AGENT" ADD CONSTRAINT "PK_DT_AGENT" PRIMARY KEY ("ID_AGENT");


CREATE TABLE "DT_AGENT_CONTROLLER"
(
  "ID_CONTROLLER" INTEGER NOT NULL,
  "CONTROLLER" VARCHAR (255)
);
ALTER TABLE "DT_AGENT_CONTROLLER" ADD CONSTRAINT "PK_DT_AGENT_CONTROLLER" PRIMARY KEY ("ID_CONTROLLER");


CREATE TABLE "BT_AGENT_CONTROLLER"
(
  "ID_AGENT" INTEGER NOT NULL,
  "ID_CONTROLLER" INTEGER NOT NULL,
  "WEIGHT" INTEGER
);
ALTER TABLE "BT_AGENT_CONTROLLER" ADD CONSTRAINT "PK_BT_AGENT_CONTROLLER" PRIMARY KEY ("ID_AGENT", "ID_CONTROLLER");




CREATE TABLE "DT_TIME"
(
  "ID_DATE" INTEGER NOT NULL,
  "DATE" VARCHAR (255),
  "MONTH_IN_YEAR" VARCHAR (255),
  "ID_MONTH_IN_YEAR" INTEGER,
  "QUARTER" VARCHAR (255),
  "ID_QUARTER" INTEGER,
  "SEMESTER" VARCHAR (255),
  "ID_SEMESTER" INTEGER,
  "YEAR" VARCHAR (255),
  "ID_YEAR" INTEGER,
  "_4_MONTH_PERIOD" VARCHAR (255),
  "ID__4_MONTH_PERIOD" INTEGER,
  "MONTH" VARCHAR (255),
  "ID_MONTH" INTEGER,
  "WEEK" VARCHAR (255),
  "ID_WEEK" INTEGER
);
ALTER TABLE "DT_TIME" ADD CONSTRAINT "PK_DT_TIME" PRIMARY KEY ("ID_DATE");




CREATE TABLE "DT_PRODUCT"
(
  "ID_SKU" INTEGER NOT NULL,
  "SKU" VARCHAR (255),
  "SUBTYPE" VARCHAR (255),
  "ID_SUBTYPE" INTEGER,
  "TYPE" VARCHAR (255),
  "ID_TYPE" INTEGER,
  "CATEGORY" VARCHAR (255),
  "ID_CATEGORY" INTEGER,
  "CUSTOMER_TYPE" VARCHAR (255),
  "ID_CUSTOMER_TYPE" INTEGER,
  "AGE_RANGE" VARCHAR (255),
  "CUSTOMER_GENDER" VARCHAR (255),
  "ID_CUSTOMER_GENDER" INTEGER,
  "SIZE" VARCHAR (255),
  "ID_SIZE" INTEGER,
  "COLOR" VARCHAR (255),
  "ID_COLOR" INTEGER,
  "MACRO_COLOR" VARCHAR (255),
  "ID_MACRO_COLOR" INTEGER,
  "BRAND" VARCHAR (255),
  "ID_BRAND" INTEGER,
  "BRAND_GROUP" VARCHAR (255),
  "ID_BRAND_GROUP" INTEGER,
  "MADE_IN" VARCHAR (255),
  "ID_MADE_IN" INTEGER
);
ALTER TABLE "DT_PRODUCT" ADD CONSTRAINT "PK_DT_PRODUCT" PRIMARY KEY ("ID_SKU");




CREATE TABLE "DT_GEOGRAPHY"
(
  "ID_CITY" INTEGER NOT NULL,
  "CITY" VARCHAR (255),
  "COUNTY" VARCHAR (255),
  "ID_COUNTY" INTEGER,
  "STATE" VARCHAR (255),
  "ID_STATE" INTEGER,
  "COUNTRY" VARCHAR (255),
  "ID_COUNTRY" INTEGER,
  "AREA" VARCHAR (255),
  "ID_AREA" INTEGER
);
ALTER TABLE "DT_GEOGRAPHY" ADD CONSTRAINT "PK_DT_GEOGRAPHY" PRIMARY KEY ("ID_CITY");




CREATE TABLE "DT_CUSTOMER"
(
  "ID_CUSTOMER" INTEGER NOT NULL,
  "CUSTOMER" VARCHAR (255),
  "BILLING_INFORMATION" VARCHAR (255),
  "ID_CITY" INTEGER,
  "SHIPPING_ADDRESS" VARCHAR (255)
);
ALTER TABLE "DT_CUSTOMER" ADD CONSTRAINT "PK_DT_CUSTOMER" PRIMARY KEY ("ID_CUSTOMER");




CREATE TABLE "DT_WAREHOUSE"
(
  "ID_WAREHOUSE" INTEGER NOT NULL,
  "WAREHOUSE" VARCHAR (255),
  "WAREHOUSE_TYPE" VARCHAR (255),
  "ID_WAREHOUSE_TYPE" INTEGER,
  "ISVIRTUAL" VARCHAR (255),
  "ID_ISVIRTUAL" INTEGER,
  "ID_CITY" INTEGER
);
ALTER TABLE "DT_WAREHOUSE" ADD CONSTRAINT "PK_DT_WAREHOUSE" PRIMARY KEY ("ID_WAREHOUSE");




CREATE TABLE "DT_STORE"
(
  "ID_STORE" INTEGER NOT NULL,
  "STORE" VARCHAR (255),
  "ISCONNECTED" VARCHAR (255),
  "ID_ISCONNECTED" INTEGER,
  "LOCATION_TYPE" VARCHAR (255),
  "ID_LOCATION_TYPE" INTEGER,
  "ID_CITY" INTEGER,
  "ADDRESS" VARCHAR (255),
  "SALES_DISTRICT" VARCHAR (255),
  "ID_SALES_DISTRICT" INTEGER
);
ALTER TABLE "DT_STORE" ADD CONSTRAINT "PK_DT_STORE" PRIMARY KEY ("ID_STORE");




CREATE TABLE "FT_HISTORICAL_ORDER"
(
  "SEASON" VARCHAR (255) NOT NULL,
  "CURRENCY" VARCHAR (255) NOT NULL,
  "ID_MONTH_IN_YEAR" INTEGER NOT NULL,
  "ID_SUBTYPE" INTEGER NOT NULL,
  "ID_COUNTRY" INTEGER NOT NULL,
  "QUANTITY" DECIMAL (18,3),
  "NET_VALUE" DECIMAL (18,3),
  "DISCOUNT_VALUE" DECIMAL (18,3),
  "VAT_VALUE" DECIMAL (18,3)
);
ALTER TABLE "FT_HISTORICAL_ORDER" ADD CONSTRAINT "PK_FT_HISTORICAL_ORDER" PRIMARY KEY ("SEASON", "CURRENCY", "ID_MONTH_IN_YEAR", "ID_SUBTYPE", "ID_COUNTRY");




CREATE TABLE "FT_INVOICE"
(
  "GOODS_ON_DELIVERY" VARCHAR (255) NOT NULL,
  "SHIPPING_CUSTOMER" INTEGER NOT NULL,
  "SEASON" VARCHAR (255) NOT NULL,
  "ID_DATE" INTEGER NOT NULL,
  "RETURN_JUSTIFICATION" VARCHAR (255) NOT NULL,
  "CURRENCY" VARCHAR (255) NOT NULL,
  "ID_SKU" INTEGER NOT NULL,
  "ID_AGENT" INTEGER NOT NULL,
  "PROFIT_CENTER" VARCHAR (255) NOT NULL,
  "VIRTUAL_WAREHOUSE" VARCHAR (255) NOT NULL,
  "DOC_TYPE" VARCHAR (255) NOT NULL,
  "BILLING_CUSTOMER" INTEGER NOT NULL,
  "QUANTITY" DECIMAL (18,3),
  "NET_VALUE" DECIMAL (18,3),
  "FIRST_COMMERCIAL_DISCOUNT" DECIMAL (18,3),
  "SECOND_COMMERCIAL_DISCOUNT" DECIMAL (18,3),
  "SELL_IN_MARGIN" DECIMAL (18,3),
  "NET_AVERAGE_PRICE" DECIMAL (18,3)
);
ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "PK_FT_INVOICE" PRIMARY KEY ("GOODS_ON_DELIVERY", "SHIPPING_CUSTOMER", "SEASON", "ID_DATE", "RETURN_JUSTIFICATION", "CURRENCY", "ID_SKU", "ID_AGENT", "PROFIT_CENTER", "VIRTUAL_WAREHOUSE", "DOC_TYPE", "BILLING_CUSTOMER");




CREATE TABLE "FT_ORDER"
(
  "ID_AGENT" INTEGER NOT NULL,
  "MERCHANDISE_TYPE" VARCHAR (255) NOT NULL,
  "SEASON" VARCHAR (255) NOT NULL,
  "ID_DATE" INTEGER NOT NULL,
  "ORDER_TYPE" VARCHAR (255) NOT NULL,
  "CURRENCY" VARCHAR (255) NOT NULL,
  "ID_SKU" INTEGER NOT NULL,
  "ID_CUSTOMER" INTEGER NOT NULL,
  "QUANTITY" DECIMAL (18,3),
  "NET_VALUE" DECIMAL (18,3),
  "DISCOUNT_VALUE" DECIMAL (18,3),
  "VAT_VALUE" DECIMAL (18,3)
);
ALTER TABLE "FT_ORDER" ADD CONSTRAINT "PK_FT_ORDER" PRIMARY KEY ("ID_AGENT", "MERCHANDISE_TYPE", "SEASON", "ID_DATE", "ORDER_TYPE", "CURRENCY", "ID_SKU", "ID_CUSTOMER");




CREATE TABLE "FT_SHOP_TICKET"
(
  "SEASON" VARCHAR (255) NOT NULL,
  "ID_DATE" INTEGER NOT NULL,
  "CURRENCY" VARCHAR (255) NOT NULL,
  "ID_AGENT" INTEGER NOT NULL,
  "ID_STORE" INTEGER NOT NULL,
  "ID_SKU" INTEGER NOT NULL,
  "QUANTITY" DECIMAL (18,3),
  "NET_VALUE" DECIMAL (18,3),
  "DISCOUNT_VALUE" DECIMAL (18,3),
  "VAT_VALUE" DECIMAL (18,3)
);
ALTER TABLE "FT_SHOP_TICKET" ADD CONSTRAINT "PK_FT_SHOP_TICKET" PRIMARY KEY ("SEASON", "ID_DATE", "CURRENCY", "ID_AGENT", "ID_STORE", "ID_SKU");




CREATE TABLE "FT_TRAFFIC_COUNTER"
(
  "ID_DATE" INTEGER NOT NULL,
  "ID_STORE" INTEGER NOT NULL,
  "HOUR" VARCHAR (255) NOT NULL,
  "TRAFFIC_COUNTER" DECIMAL (18,3),
  "PEOPLETICKETS_RATIO" DECIMAL (18,3)
);
ALTER TABLE "FT_TRAFFIC_COUNTER" ADD CONSTRAINT "PK_FT_TRAFFIC_COUNTER" PRIMARY KEY ("ID_DATE", "ID_STORE", "HOUR");




CREATE TABLE "FT_THIRD_PARTY_WAREHOUSE_STOCK"
(
  "ID_SKU" INTEGER NOT NULL,
  "ID_DATE" INTEGER NOT NULL,
  "ID_WAREHOUSE_TYPE" INTEGER NOT NULL,
  "ID_CITY" INTEGER NOT NULL,
  "QUANTITY_IN_STOCK" DECIMAL (18,3)
);
ALTER TABLE "FT_THIRD_PARTY_WAREHOUSE_STOCK" ADD CONSTRAINT "PK_FT_THIRD_PARTY_WAREHOUSE_STOCK" PRIMARY KEY ("ID_SKU", "ID_DATE", "ID_WAREHOUSE_TYPE", "ID_CITY");




CREATE TABLE "FT_WAREHOUSE_MOVEMENT"
(
  "CAUSE" VARCHAR (255) NOT NULL,
  "MERCHANDISE_TYPE" VARCHAR (255) NOT NULL,
  "IN_DATE" INTEGER NOT NULL,
  "ID_WAREHOUSE" INTEGER NOT NULL,
  "ID_SKU" INTEGER NOT NULL,
  "OUT_DATE" INTEGER NOT NULL,
  "QUANTITY" DECIMAL (18,3)
);
ALTER TABLE "FT_WAREHOUSE_MOVEMENT" ADD CONSTRAINT "PK_FT_WAREHOUSE_MOVEMENT" PRIMARY KEY ("CAUSE", "MERCHANDISE_TYPE", "IN_DATE", "ID_WAREHOUSE", "ID_SKU", "OUT_DATE");




CREATE TABLE "FT_WAREHOUSE_STOCK"
(
  "ID_SKU" INTEGER NOT NULL,
  "MERCHANDISE_TYPE" VARCHAR (255) NOT NULL,
  "ID_DATE" INTEGER NOT NULL,
  "ID_WAREHOUSE" INTEGER NOT NULL,
  "QUANTITY_IN_STOCK" DECIMAL (18,3)
);
ALTER TABLE "FT_WAREHOUSE_STOCK" ADD CONSTRAINT "PK_FT_WAREHOUSE_STOCK" PRIMARY KEY ("ID_SKU", "MERCHANDISE_TYPE", "ID_DATE", "ID_WAREHOUSE");







ALTER TABLE "BT_AGENT_CONTROLLER" ADD CONSTRAINT "FK_BT_AGNT_CNTR_ID_CNTR_ID_CN" FOREIGN KEY ("ID_CONTROLLER") REFERENCES "DT_AGENT_CONTROLLER" ("ID_CONTROLLER");
ALTER TABLE "BT_AGENT_CONTROLLER" ADD CONSTRAINT "FK_BT_AGNT_CNTR_ID_AGNT_ID_AG" FOREIGN KEY ("ID_AGENT") REFERENCES "DT_AGENT" ("ID_AGENT");




ALTER TABLE "DT_CUSTOMER" ADD CONSTRAINT "FK_DT_CSTM_ID_CITY_ID_CITY" FOREIGN KEY ("ID_CITY") REFERENCES "DT_GEOGRAPHY" ("ID_CITY");

ALTER TABLE "DT_WAREHOUSE" ADD CONSTRAINT "FK_DT_WRHS_ID_CITY_ID_CITY" FOREIGN KEY ("ID_CITY") REFERENCES "DT_GEOGRAPHY" ("ID_CITY");

ALTER TABLE "DT_STORE" ADD CONSTRAINT "FK_DT_STORE_ID_CITY_ID_CITY" FOREIGN KEY ("ID_CITY") REFERENCES "DT_GEOGRAPHY" ("ID_CITY");


ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "FK_FT_INVC_SHPP_CSTM_ID_CSTM" FOREIGN KEY ("SHIPPING_CUSTOMER") REFERENCES "DT_CUSTOMER" ("ID_CUSTOMER");
ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "FK_FT_INVOICE_ID_DATE_ID_DATE" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "FK_FT_INVOICE_ID_SKU_ID_SKU" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");
ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "FK_FT_INVOICE_ID_AGNT_ID_AGNT" FOREIGN KEY ("ID_AGENT") REFERENCES "DT_AGENT" ("ID_AGENT");
ALTER TABLE "FT_INVOICE" ADD CONSTRAINT "FK_FT_INVC_BLLN_CSTM_ID_CSTM" FOREIGN KEY ("BILLING_CUSTOMER") REFERENCES "DT_CUSTOMER" ("ID_CUSTOMER");

ALTER TABLE "FT_ORDER" ADD CONSTRAINT "FK_FT_ORDER_ID_AGENT_ID_AGENT" FOREIGN KEY ("ID_AGENT") REFERENCES "DT_AGENT" ("ID_AGENT");
ALTER TABLE "FT_ORDER" ADD CONSTRAINT "FK_FT_ORDER_ID_DATE_ID_DATE" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_ORDER" ADD CONSTRAINT "FK_FT_ORDER_ID_SKU_ID_SKU" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");
ALTER TABLE "FT_ORDER" ADD CONSTRAINT "FK_FT_ORDER_ID_CSTM_ID_CSTM" FOREIGN KEY ("ID_CUSTOMER") REFERENCES "DT_CUSTOMER" ("ID_CUSTOMER");

ALTER TABLE "FT_SHOP_TICKET" ADD CONSTRAINT "FK_FT_SHOP_TCKT_ID_DATE_ID_DA" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_SHOP_TICKET" ADD CONSTRAINT "FK_FT_SHOP_TCKT_ID_AGNT_ID_AG" FOREIGN KEY ("ID_AGENT") REFERENCES "DT_AGENT" ("ID_AGENT");
ALTER TABLE "FT_SHOP_TICKET" ADD CONSTRAINT "FK_FT_SHOP_TCKT_ID_STR_ID_STR" FOREIGN KEY ("ID_STORE") REFERENCES "DT_STORE" ("ID_STORE");
ALTER TABLE "FT_SHOP_TICKET" ADD CONSTRAINT "FK_FT_SHOP_TCKT_ID_SKU_ID_SKU" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");

ALTER TABLE "FT_TRAFFIC_COUNTER" ADD CONSTRAINT "FK_FT_TRFF_CNTR_ID_DATE_ID_DA" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_TRAFFIC_COUNTER" ADD CONSTRAINT "FK_FT_TRFF_CNTR_ID_STR_ID_STR" FOREIGN KEY ("ID_STORE") REFERENCES "DT_STORE" ("ID_STORE");

ALTER TABLE "FT_THIRD_PARTY_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_THRD_PRTY_WRHS_STCK_ID" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");
ALTER TABLE "FT_THIRD_PARTY_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_THRD_PRTY_WRHS_STCK_ID_2" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_THIRD_PARTY_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_THRD_PRTY_WRHS_STCK_ID_3" FOREIGN KEY ("ID_CITY") REFERENCES "DT_GEOGRAPHY" ("ID_CITY");

ALTER TABLE "FT_WAREHOUSE_MOVEMENT" ADD CONSTRAINT "FK_FT_WRHS_MVMN_IN_DATE_ID_DA" FOREIGN KEY ("IN_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_WAREHOUSE_MOVEMENT" ADD CONSTRAINT "FK_FT_WRHS_MVMN_ID_WRHS_ID_WR" FOREIGN KEY ("ID_WAREHOUSE") REFERENCES "DT_WAREHOUSE" ("ID_WAREHOUSE");
ALTER TABLE "FT_WAREHOUSE_MOVEMENT" ADD CONSTRAINT "FK_FT_WRHS_MVMN_ID_SKU_ID_SKU" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");
ALTER TABLE "FT_WAREHOUSE_MOVEMENT" ADD CONSTRAINT "FK_FT_WRHS_MVMN_OUT_DATE_ID_D" FOREIGN KEY ("OUT_DATE") REFERENCES "DT_TIME" ("ID_DATE");

ALTER TABLE "FT_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_WRHS_STCK_ID_SKU_ID_SKU" FOREIGN KEY ("ID_SKU") REFERENCES "DT_PRODUCT" ("ID_SKU");
ALTER TABLE "FT_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_WRHS_STCK_ID_DATE_ID_DA" FOREIGN KEY ("ID_DATE") REFERENCES "DT_TIME" ("ID_DATE");
ALTER TABLE "FT_WAREHOUSE_STOCK" ADD CONSTRAINT "FK_FT_WRHS_STCK_ID_WRHS_ID_WR" FOREIGN KEY ("ID_WAREHOUSE") REFERENCES "DT_WAREHOUSE" ("ID_WAREHOUSE");


-- DROP TABLE IF EXISTS "DT_AGENT" CASCADE;
-- DROP TABLE IF EXISTS "DT_AGENT_CONTROLLER" CASCADE;
-- DROP TABLE IF EXISTS "BT_AGENT_CONTROLLER" CASCADE;
-- DROP TABLE IF EXISTS "DT_TIME" CASCADE;
-- DROP TABLE IF EXISTS "DT_PRODUCT" CASCADE;
-- DROP TABLE IF EXISTS "DT_GEOGRAPHY" CASCADE;
-- DROP TABLE IF EXISTS "DT_CUSTOMER" CASCADE;
-- DROP TABLE IF EXISTS "DT_WAREHOUSE" CASCADE;
-- DROP TABLE IF EXISTS "DT_STORE" CASCADE;
-- DROP TABLE IF EXISTS "FT_HISTORICAL_ORDER" CASCADE;
-- DROP TABLE IF EXISTS "FT_INVOICE" CASCADE;
-- DROP TABLE IF EXISTS "FT_ORDER" CASCADE;
-- DROP TABLE IF EXISTS "FT_SHOP_TICKET" CASCADE;
-- DROP TABLE IF EXISTS "FT_TRAFFIC_COUNTER" CASCADE;
-- DROP TABLE IF EXISTS "FT_THIRD_PARTY_WAREHOUSE_STOCK" CASCADE;
-- DROP TABLE IF EXISTS "FT_WAREHOUSE_MOVEMENT" CASCADE;
-- DROP TABLE IF EXISTS "FT_WAREHOUSE_STOCK" CASCADE;




CREATE VIEW "DTV_TIME_MONTH_IN_YEAR" AS 
SELECT DISTINCT 
  "ID_MONTH_IN_YEAR",
  "MONTH_IN_YEAR",
  "QUARTER",
  "SEMESTER",
  "YEAR",
  "_4_MONTH_PERIOD",
  "MONTH"
 FROM "DT_TIME" ; 



CREATE VIEW "DTV_PRODUCT_SUBTYPE" AS 
SELECT DISTINCT 
  "ID_SUBTYPE",
  "SUBTYPE",
  "TYPE",
  "CATEGORY",
  "CUSTOMER_TYPE",
  "AGE_RANGE"
 FROM "DT_PRODUCT" ; 



CREATE VIEW "DTV_GEOGRAPHY_COUNTRY" AS 
SELECT DISTINCT 
  "ID_COUNTRY",
  "COUNTRY",
  "AREA"
 FROM "DT_GEOGRAPHY" ; 



CREATE VIEW "DTV_WAREHOUSE_WAREHOUSE_TYPE" AS 
SELECT DISTINCT 
  "ID_WAREHOUSE_TYPE",
  "WAREHOUSE_TYPE"
 FROM "DT_WAREHOUSE" ; 


